version: "3"

services:
  db:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    env_file:
      - .env.development
    volumes:
      - postis:/var/lib/postgresql/data
  dbtest:
    image: postgres:11-alpine
    ports:
      - 5434:5432
    env_file:
      - .env.test
    volumes:
      - postisDbTest:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postis:
  postisDbTest:
